<?php  
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!--- START 以上内容不需更改，保证该TPL页内的标签匹配即可 --->
<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>

<div style="border:0px;padding-bottom:5px;height:auto">
    <form action="addActive" method="GET" style="margin-bottom:0px">
    <div style="float:left;margin-right:5px">
        <label> 选择起始时间 </label>
        <input type="text" id="start_date" name="start_date" value="<?php echo @$_GET['start_date'];?>" placeholder="起始时间" >
    </div>
    <div style="float:left;margin-right:5px">
        <label>选择结束时间</label>
        <input type="text" id="end_date" name="end_date" value="<?php echo @$_GET['end_date'];?>" placeholder="结束时间" > 
    </div>
    <div class="btn-toolbar" style="padding-top:15px;padding-bottom:0px;margin-bottom:0px;float:left">
        <button type="submit" class="btn btn-primary"><strong>检索</strong></button>
    </div>
    <div style="clear:both;"></div>
    </form>
</div>
    <div class="block">
        <a href="#page-stats" class="block-heading" data-toggle="collapse">数据记录</a>
        <div id="page-stats" class="block-body collapse in">
               <table class="table table-striped">
              <thead>
                <tr>
                    <th style="text-align:center;">日期</th>
                    <th style="text-align:center;">活跃用户</th>
                    <th style="text-align:center;">男活跃</th>
                    <th style="text-align:center;">女活跃</th>
                    <th style="text-align:center;">新增用户</th>
                    <th style="text-align:center;">男新增</th>
                    <th style="text-align:center;">女新增</th>
                    <th style="text-align:center;">Android新增</th>
                    <th style="text-align:center;">ios新增</th>
                    <th style="text-align:center;">H5新增</th>
                    <!--<th style="width:48px">手机号注册</th>
                    <th style="width:32px">QQ注册</th>-->
                    <th style="text-align:center;">微信注册</th>
                    <!--<th style="width:37px">微博注册</th>-->
                </tr>
              </thead>
              <tbody>
                <?php foreach (@$adds as $add) {?>
                    <tr>
                    <td style="text-align:center;"><?php echo @$add['stat_date'];?></td>
                    <td style="text-align:center;"><?php echo @array_sum(@$add['active']['d']['g'])?></td>
                    <td style="text-align:center;"><?php echo @$add['active']['d']['g'][1]?></td>
                    <td style="text-align:center;"><?php echo @$add['active']['d']['g'][0]?></td>
                    <td style="text-align:center;"><?php echo @array_sum($add['data']['g']);?></td>
                    <td style="text-align:center;"><?php echo @$add['data']['g'][1];?></td>
                    <td style="text-align:center;"><?php echo @$add['data']['g'][0];?></td>
                    <td style="text-align:center;"><?php echo @$add['data']['p'][1];?></td>
                    <td style="text-align:center;"><?php echo @$add['data']['p'][0];?></td>
                    <td style="text-align:center;"><?php echo (@$add['data']['p'][2]+@$add['data']['p'][3]+@$add['data']['p'][4]); ?></td>
                    <!--<td style="text-align:center"><?php //echo $add[1]['t'][0];?></td>
                    <td style="text-align:center"><?php //echo $add[1]['t'][1];?></td>-->
                    <td style="text-align:center;"><?php echo @$add['data']['t'][3];?></td>
                    <!-- <td style="text-align:center"><?php //echo $add[1]['t'][2];?></td>-->
                    
                    </tr>
                <?php }?>
              </tbody>
            </table>
                <!--- START 分页模板 --->
                <?php echo $page_html;?>
                <!--- END --->
        </div>
    </div>

<script>
$(function() {
	var date=$( "#start_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
$(function() {
	var date=$( "#end_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
$(function() {
	var html='';
	html+='<option value="0">--请选择--</option>';
	html+='<option value="1">日活跃用户</option>';
	html+='<option value="2">男日活跃</option>';
	html+='<option value="3">女日活跃</option>';
	html+='<option value="4">新增用户</option>';
	html+='<option value="5">男日新增</option>';
	html+='<option value="6">女日新增</option>';
	html+='<option value="7">Android日新增</option>';
	html+='<option value="8">IOS日新增</option>';
	//html+='<option value="9">手机号注册</option>';
	//html+='<option value="10">QQ注册</option>';
	html+='<option value="9">微信注册</option>';
	//html+='<option value="12">微博注册</option>';
	//html+='<option value="10">H5日新增</option>';
	$('#classify').html(html);
	
})
$(function() {
	$('select').change(function(){
		var start_date=$('#start_date').val();
        var end_date=$('#end_date').val();
        var classify=$(this).val();
        $.ajax({
            'type':'post',
            'url':'addActive',
            'data':{'start_date':start_date,
                    'end_date':end_date,
                    'classify':classify},
            'success':function(e){
                    $('#sum').val(e);
                }
            },'json')
	})
    
})
</script>
	
<!--- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 --->
<?php include(dirname(__DIR__)."/footer.phtml"); ?>