<?php 
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!--- START 以上内容不需更改，保证该TPL页内的标签匹配即可 --->
<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>

<div style="border:0px;padding-bottom:5px;height:auto">
    <form action="commentLike" method="GET" style="margin-bottom:0px">
    <div style="float:left;margin-right:5px">
        <label> 选择起始时间 </label>
        <input type="text" id="start_date" name="start_date" value="<?php echo @$_GET['start_date'];?>" placeholder="起始时间" >
    </div>
    <div style="float:left;margin-right:5px">
        <label>选择结束时间</label>
        <input type="text" id="end_date" name="end_date" value="<?php echo @$_GET['end_date'];?>" placeholder="结束时间" > 
    </div>
    <div class="btn-toolbar" style="padding-top:15px;padding-bottom:0px;margin-bottom:0px;float:left">
        <button type="submit" class="btn btn-primary"><strong>检索</strong></button>
    </div>
    <div style="clear:both;"></div>
    </form>
</div>
    <div class="block">
        <a href="#page-stats" class="block-heading" data-toggle="collapse">数据记录</a>
        <div id="page-stats" class="block-body collapse in">
               <table class="table table-striped">
              <thead>
                <tr>
                    <th style="text-align:center;">日期</th>
                    <th style="text-align:center;">总赞数量</th>
                    <th style="text-align:center;">总评论数量</th>
                    <th style="text-align:center;">男发起赞</th>
                    <th style="text-align:center;">女发起赞</th>
                    <th style="text-align:center;">男发起评论</th>
                    <th style="text-align:center;">女发起评论</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach (@$commentLikes as $commentLike) { ?>
                    <tr>
                    <td style="text-align:center;"><?php echo @$commentLike['stat_date']?></td>
                    <td style="text-align:center;"><?php if (@array_sum(@$commentLike['data']['l']['g'])) { echo @array_sum(@$commentLike['data']['l']['g']);} else {echo 0;}?></td>
                    <td style="text-align:center;"><?php if (@array_sum(@$commentLike['data']['c']['g'])) { echo @array_sum(@$commentLike['data']['c']['g']);} else {echo 0;}?></td>
                    <td style="text-align:center;"><?php if (@$commentLike['data']['l']['g'][1]) { echo @$commentLike['data']['l']['g'][1];} else {echo 0;}?></td>
                    <td style="text-align:center;"><?php if (@$commentLike['data']['l']['g'][0]) { echo @$commentLike['data']['l']['g'][0];} else {echo 0;}?></td>
                    <td style="text-align:center;"><?php if (@$commentLike['data']['c']['g'][1]) { echo @$commentLike['data']['c']['g'][1];} else {echo 0;}?></td>
                    <td style="text-align:center;"><?php if (@$commentLike['data']['c']['g'][0]) { echo @$commentLike['data']['c']['g'][0];} else {echo 0;}?></td>
                    </tr>
                <?php }?>
              </tbody>
            </table>
                <!--- START 分页模板 --->
                <?php echo $page_html;?>
                <!--- END --->
        </div>
    </div>

<script>
$(function() {
	var date=$( "#start_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
$(function() {
	var date=$( "#end_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
</script>
	
<!--- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 --->
<?php include(dirname(__DIR__)."/footer.phtml"); ?>