<?php  
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!--- START 以上内容不需更改，保证该TPL页内的标签匹配即可 --->
<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>
    <div class="block">
        <a href="#page-stats" class="block-heading" data-toggle="collapse">有效活动详情数据</a>
        <div id="page-stats" class="block-body collapse in">
               <table class="table table-striped">
              <thead>
                <tr>
                    <th style="text-align:center">日期</th>
                    <th style="text-align:center">详情</th>
                </tr>
              </thead>
              <tbody>
                  <tr>
                      <td style="text-align:center"><?php echo $imp['stat_date']?></td>
                      <td>
                          <?php foreach ($imp[0] as $v) {?>
                              <?php echo $v['key'].'人参与的活动'.$v['count'].'个:'?><?php foreach (@$v['value'] as $v2) {?><a href="javascript:void(0);" onclick="window.location.href='/Console/Event/events?event_id=<?php echo $v2;?>'"><?php echo $v2.','?></a><?php }?><br>
                          <?php }?>
                      </td>
                  </tr>
              </tbody>
            </table>
                <!--- START 分页模板 --->
                <?php //echo $page_html;?>
                <!--- END --->
        </div>
    </div>

<script>
$(function() {
	$('div.detail').parents('tr').hide();
})
function detail(obj) {
	$(obj).parents('tr').next().toggle();
}
$(function() {
	var date=$( "#start_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
$(function() {
	var date=$( "#end_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
</script>
	
<!--- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 --->
<?php include(dirname(__DIR__)."/footer.phtml"); ?>