<?php  
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!--- START 以上内容不需更改，保证该TPL页内的标签匹配即可 --->
<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>

<div style="border:0px;padding-bottom:5px;height:auto">
    <form action="invite" method="GET" style="margin-bottom:0px">
    <div style="float:left;margin-right:5px">
        <label> 分类 </label>
        <select name="classify">
            <option value="0" selected <?php if (@$_GET['classify'] == 0) { echo 'selected';}?>>总计</option>
            <option value="1" <?php if (@$_GET['classify'] == 1) { echo 'selected';}?>>新增用户</option>
            <option value="2" <?php if (@$_GET['classify'] == 2) { echo 'selected';}?>>IOS</option>
            <option value="3" <?php if (@$_GET['classify'] == 3) { echo 'selected';}?>>Android</option>
        </select>
    </div>
    <div style="float:left;margin-right:5px">
        <label> 选择起始时间 </label>
        <input type="text" id="start_date" name="start_date" value="<?php echo @$_GET['start_date'];?>" placeholder="起始时间" >
    </div>
    <div style="float:left;margin-right:5px">
        <label>选择结束时间</label>
        <input type="text" id="end_date" name="end_date" value="<?php echo @$_GET['end_date'];?>" placeholder="结束时间" > 
    </div>
    <div class="btn-toolbar" style="padding-top:15px;padding-bottom:0px;margin-bottom:0px;float:left">
        <button type="submit" class="btn btn-primary"><strong>检索</strong></button>
    </div>
    <!-- <div style="float:left;margin-left:5px">
    <label> 分类</label>
    <select id="classify">
    </select>
    </div>
    <div style="float:left;margin-left:5px">
        <label>总计</label>
        <input type="text" id="sum" placeholder="总计" disabled="disabled"> 
    </div>
    -->
    <div style="clear:both;"></div>
    </form>
</div>
    <div class="block">
        <a href="#page-stats" class="block-heading" data-toggle="collapse">数据记录</a>
        <?php if (@$_GET['classify'] == 0 || @$_GET['classify'] == NULL) {?>
        <div id="page-stats" class="block-body collapse in">
               <table class="table table-striped">
              <thead>
                <tr>
                    <th style="text-align:center">日期</th>
                    <th style="text-align:center">邀请按钮点击数</th>
                    <th style="text-align:center">邀请好友人数</th>
                    <th style="text-align:center">邀请好友次数</th>
                    <th style="text-align:center">受邀加入活动人数</th>
                    <!--<th>接受邀请启动数</th>
                    <th>接受邀请注册数</th>-->
                    <th style="text-align:center">H5上传人数</th>
                    <th style="text-align:center">H5上传照片</th>
                    <th style="text-align:center">微信邀请</th>
                    <th style="text-align:center">QQ邀请</th>
                    <th style="text-align:center">通讯录邀请</th>
                    <th style="text-align:center">邮件邀请</th>
                    <th style="text-align:center">链接邀请</th>
                    <th style="text-align:center">二维码邀请</th>
                </tr>
              </thead>
              <tbody>
                  <?php foreach ($stat_datas as $item) {?>
                  <tr>
                      <td style="text-align:center"><?php echo @$item['stat_date']?></td>
                      <td style="text-align:center"><?php echo (@$item['data']['cei'][0]['pv']+@$item['data']['cei'][1]['pv'])?></td>
                      <td style="text-align:center"><?php echo (@$item['data']['invite'][0]['uv']+@$item['data']['invite'][1]['uv'])?></td>
                      <td style="text-align:center"><?php echo (@$item['data']['invite'][0]['pv']+@$item['data']['invite'][1]['pv'])?></td>
                      <td style="text-align:center"><?php if (@$item['invited_actives'] >= 0) {echo @$item['invited_actives'];} else {echo 0;}?></td>
                      <!--<td>&nbsp;</td>
                      <td><?php //echo @$item['h5']?></td>-->
                      <td style="text-align:center"><?php if (@$item['u_uv']) {echo @$item['u_uv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['u_pv']) {echo @$item['u_pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php echo (@$item['data']['ci_wx'][0]['pv']+@$item['data']['ci_wx'][1]['pv'])?></td>
                      <td style="text-align:center"><?php echo (@$item['data']['ci_qq'][0]['pv']+@$item['data']['ci_qq'][1]['pv'])?></td>
                      <td style="text-align:center"><?php echo (@$item['data']['cic'][0]['pv']+@$item['data']['cic'][1]['pv'])?></td>
                      <td style="text-align:center"><?php echo (@$item['data']['cie'][0]['pv']+@$item['data']['cie'][1]['pv'])?></td>
                      <td style="text-align:center"><?php echo (@$item['data']['ciu'][0]['pv']+@$item['data']['ciu'][1]['pv'])?></td>
                      <td style="text-align:center"><?php echo (@$item['data']['ciq'][0]['pv']+@$item['data']['ciq'][1]['pv'])?></td>
                  </tr>
                  <?php }?>
              </tbody>
            </table>
                <!--- START 分页模板 --->
                <?php echo $page_html;?>
                <!--- END --->
        </div>
        <?php } elseif (@$_GET['classify'] == 1) {?>
        <div id="page-stats" class="block-body collapse in">
               <table class="table table-striped">
              <thead>
                <tr>
                    <th style="text-align:center">日期</th>
                    <th style="text-align:center">邀请按钮点击数</th>
                    <th style="text-align:center">邀请好友人数</th>
                    <th style="text-align:center">邀请好友次数</th>
                    <!--<th>接受邀请启动数</th>
                    <th>接受邀请注册数</th>-->
                    <th style="text-align:center">H5上传人数</th>
                    <th style="text-align:center">H5上传照片</th>
                </tr>
              </thead>
              <tbody>
                  <?php foreach ($adds as $add) {?>
                  <tr>
                      <td style="text-align:center"><?php echo @$add['stat_date']?></td>
                      <td style="text-align:center"><?php echo (@$add['data']['cei'][0]['pv']+@$add['data']['cei'][1]['pv'])?></td>
                      <td style="text-align:center"><?php echo (@$add['data']['invite'][0]['uv']+@$add['data']['invite'][1]['uv'])?></td>
                      <td style="text-align:center"><?php echo (@$add['data']['invite'][0]['pv']+@$add['data']['invite'][1]['pv'])?></td>
                      <!--<td>&nbsp;</td>
                      <td><?php //echo @$item['h5']?></td>-->
                      <td style="text-align:center"><?php if (@$add['data']['u']['uv']) {echo @$add['data']['u']['uv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$add['data']['u']['pv']) {echo @$add['data']['u']['pv'];} else {echo 0;}?></td>
                  </tr>
                  <?php }?>
              </tbody>
            </table>
                <!--- START 分页模板 --->
                <?php echo $page_html;?>
                <!--- END --->
        </div>
        <?php } elseif (@$_GET['classify'] == 2) {?>
        <div id="page-stats" class="block-body collapse in">
               <table class="table table-striped">
              <thead>
                <tr>
                    <th style="text-align:center">日期</th>
                    <th style="text-align:center">邀请按钮点击数</th>
                    <th style="text-align:center">邀请好友人数</th>
                    <th style="text-align:center">邀请好友次数</th>
                    <!--<th>接受邀请启动数</th>
                    <th>接受邀请注册数</th>-->
                    <th style="text-align:center">微信邀请</th>
                    <th style="text-align:center">QQ邀请</th>
                    <th style="text-align:center">通讯录邀请</th>
                    <th style="text-align:center">邮件邀请</th>
                    <th style="text-align:center">链接邀请</th>
                    <th style="text-align:center">二维码邀请</th>
                </tr>
              </thead>
              <tbody>
                  <?php foreach ($stat_datas as $item) {?>
                  <tr>
                      <td style="text-align:center"><?php echo @$item['stat_date']?></td>
                      <td style="text-align:center"><?php if (@$item['data']['cei'][0]['pv']) {echo @$item['data']['cei'][0]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['invite'][0]['uv']) {echo @$item['data']['invite'][0]['uv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['invite'][0]['pv']) {echo @$item['data']['invite'][0]['pv'];} else {echo 0;}?></td>
                      <!--<td>&nbsp;</td>
                      <td><?php //echo @$item['h5']?></td>-->
                      <td style="text-align:center"><?php if (@$item['data']['ci_wx'][0]['pv']) {echo @$item['data']['ci_wx'][0]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['ci_qq'][0]['pv']) {echo @$item['data']['ci_qq'][0]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['cic'][0]['pv']) {echo @$item['data']['cic'][0]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['cie'][0]['pv']) {echo @$item['data']['cie'][0]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['ciu'][0]['pv']) {echo @$item['data']['ciu'][0]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['ciq'][0]['pv']) {echo @$item['data']['ciq'][0]['pv'];} else {echo 0;}?></td>
                  </tr>
                  <?php }?>
              </tbody>
            </table>
                <!--- START 分页模板 --->
                <?php echo $page_html;?>
                <!--- END --->
        </div>
        <?php } elseif (@$_GET['classify'] == 3) {?>
        <div id="page-stats" class="block-body collapse in">
               <table class="table table-striped">
              <thead>
                <tr>
                    <th style="text-align:center">日期</th>
                    <th style="text-align:center">邀请按钮点击数</th>
                    <th style="text-align:center">邀请好友人数</th>
                    <th style="text-align:center">邀请好友次数</th>
                    <!--<th>接受邀请启动数</th>
                    <th>接受邀请注册数</th>-->
                    <th style="text-align:center">微信邀请</th>
                    <th style="text-align:center">QQ邀请</th>
                    <th style="text-align:center">通讯录邀请</th>
                    <th style="text-align:center">邮件邀请</th>
                    <th style="text-align:center">链接邀请</th>
                    <th style="text-align:center">二维码邀请</th>
                </tr>
              </thead>
              <tbody>
                  <?php foreach ($stat_datas as $item) {?>
                  <tr>
                      <td style="text-align:center"><?php echo @$item['stat_date']?></td>
                      <td style="text-align:center"><?php if (@$item['data']['cei'][1]['pv']) {echo @$item['data']['cei'][1]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['invite'][1]['uv']) {echo @$item['data']['invite'][1]['uv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['invite'][1]['pv']) {echo @$item['data']['invite'][1]['pv'];} else {echo 0;}?></td>
                      <!--<td>&nbsp;</td>
                      <td><?php //echo @$item['h5']?></td>-->
                      <td style="text-align:center"><?php if (@$item['data']['ci_wx'][1]['pv']) {echo @$item['data']['ci_wx'][1]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['ci_qq'][1]['pv']) {echo @$item['data']['ci_qq'][1]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['cic'][1]['pv']) {echo @$item['data']['cic'][1]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['cie'][1]['pv']) {echo @$item['data']['cie'][1]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['ciu'][1]['pv']) {echo @$item['data']['ciu'][1]['pv'];} else {echo 0;}?></td>
                      <td style="text-align:center"><?php if (@$item['data']['ciq'][1]['pv']) {echo @$item['data']['ciq'][1]['pv'];} else {echo 0;}?></td>
                  </tr>
                  <?php }?>
              </tbody>
            </table>
                <!--- START 分页模板 --->
                <?php echo $page_html;?>
                <!--- END --->
        </div>
        <?php }?>
    </div>

<script>
$(function() {
	var date=$( "#start_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
$(function() {
	var date=$( "#end_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
$(function() {
	var html='';
	html+='<option value="0">--请选择--</option>';
	html+='<option value="1">邀请好友次数</option>';
	html+='<option value="2">微信邀请</option>';
	html+='<option value="3">QQ邀请</option>';
	html+='<option value="4">通讯录邀请</option>';
	html+='<option value="5">邮件邀请</option>';
	html+='<option value="6">链接邀请</option>';
	html+='<option value="7">二维码邀请</option>';
	html+='<option value="8">分享按钮点击数</option>';
	html+='<option value="9">邀请按钮点击数</option>';
	//$('#classify').html(html);
	
})
$(function() {
	$('select').change(function(){
		var start_date=$('#start_date').val();
        var end_date=$('#end_date').val();
        var classify=$(this).val();
        $.ajax({
            'type':'post',
            'url':'invite',
            'data':{'start_date':start_date,
                    'end_date':end_date,
                    'classify':classify},
            'success':function(e){
                    $('#sum').val(e);
                }
            },'json')
	})
    
})
</script>
	
<!--- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 --->
<?php include(dirname(__DIR__)."/footer.phtml"); ?>