<?php 
include (dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>  
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->
<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>
    <div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">请填写功能资料</a></li>
    </ul>	

    <div id="myTabContent" class="tab-content">
          <div class="tab-pane active in" id="home">
           <form id="tab" method="post" action="">
                <label>名称<i class="label label-important">*必填项</i></label>
                <input type="text" name="menuName" value="" class="input-xlarge" required="true" autofocus="true">
                <label>链接 <span class="label label-important">不可重复，以Console/开头的相对路径</span></label>
                <input type="text" name="menuUrl" value="" class="input-xlarge" placeholder="Console/"  required="true" >
                <label>所属模块<i class="label label-important">*必填项</i></label>
                <select name="moduleId" id="DropDownTimezone" class="input-xlarge">
                    <?php
                       foreach($moduleOpts as $key=>$opts){
                           echo "<option value=$key>$opts</option>";
                       }
                    ?>
                </select>
                <label>是否左侧菜单栏显示</label>
                <select name="isShow" class="input-xlarge" >
                <option value="1" selected >是</option>
                    <option value="0">否</option>
                </select>
                
                <label>所属菜单</label>
                 <select name="fatherMenu" id="DropDownTimezone" class="input-xlarge">
                <?php
                   echo "<option value=0 >无</option>";
                  foreach ($fatherMenuOpts  as $key=>$fatherMenus) {
                        foreach ($fatherMenus as $k=>$fathermenuInfo) {
                            echo "<option value=$k>$fathermenuInfo</option>";
                        }
                    }
                ?>
                </select>
                <label>是否允许快捷菜单 <span class="label label-important">修改/ 删除类链接不允许</span></label>
                <select name="shortcutAllowed" class="input-xlarge" >
                    <option value="1" selected>是</option>
                    <option value="0">否</option>
                </select>				
                <label>描述</label>
                <textarea name="menuDesc" rows="3" class="input-xlarge"></textarea>
                <div class="btn-toolbar">
                <button type="submit" class="btn btn-primary"><strong>提交</strong></button>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 -->
<?php 
include (dirname(__DIR__).'/footer.phtml');
?>