<?php 
include (dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>  
<div class="well">
    <ul class="nav ">
       <li class="active"><a data-toggle="tab">菜单模块链接列表</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
          <div class="tab-pane active in" >
           <form id="tab" method="post" action="lists">
                <table class="table table-striped">
              <thead>
                <tr>
                    <th><input type="checkbox" id="checkAll" >全选</th>
                    <th>ID</th>
                    <th>名称</th>
                    <th>URL</th>
                    <th>模块ID</th>
                    <th >菜单</th>
                    <th >是否在线</th>
                    <th >快捷菜单</th>
                    <th>描述</th>
                </tr>
              </thead>
              <tbody>
               <?php 
                    foreach($menu as $menuInfo){
               ?>
                <tr>
                    <td>
                    <?php 
                        if ($menuInfo['menu_id'] <=100 ) {   
                    ?>
                    <input type="checkbox" name="menu_ids[]" value="<?php echo $menuInfo['menu_id']; ?>" disabled>
                    <?php 
                        } else {
                    ?>
                    <input type="checkbox" name="menu_ids[]" value="<?php echo $menuInfo['menu_id']; ?> " >
                    <?php 
                        }
                    ?>
                    </td>
                    <td> <?php echo $menuInfo['menu_id']; ?> </td>
                    <td> <?php echo $menuInfo['menu_name']; ?> </td>
                    <td> <?php echo $menuInfo['menu_url']; ?> </td>
                    <td> <?php echo $menuInfo['module_id']; ?> </td>
                    <td>
                        <?php 
                           if ($menuInfo['is_show']){
                                echo '是';
                            } else {
                                echo '否';
                            }
                        ?>
                    </td>
                    <td>
                        <?php
                            if ($menuInfo['online']) {
                                    echo '在线';
                            } else {
                                    echo '已下线';
                            }
                        ?>
                    </td>
                    <td>
                        <?php
                            if ($menuInfo['shortcut_allowed']) {
                                echo '允许';
                            } else {
                                echo '不允许';
                            }
                        ?>
                    </td>
                    <td>
                    <?php 
                        echo $menuInfo['menu_desc'];
                    ?>
                </td>
                </tr>
                <?php 
                    }
                ?>
              </tbody>
            </table> 
            <label>选择菜单模块</label>
                <?php 
                    if ($menuInfo['module_id'] >= 1) {
                ?>
                <select name="mid" id="DropDownTimezone" class="input-xlarge">
                   <?php
                       foreach($moduleOptions as $key=>$options){
                           	echo "<option value=$key>$options</option>";
                       }
                    ?>
                </select>
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-info"><strong>修改菜单模块</strong></button>
                </div>
                <?php 
                    }
                ?>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#checkAll").click(function(){
     if($(this).attr("checked")){
     $("input[name='menu_ids[]']").attr("checked",$(this).attr("checked"));
     }else{
       $("input[name='menu_ids[]']").attr("checked",false);
     }
});
</script>
<?php 
include (dirname(__DIR__).'/footer.phtml');
?>
