<?php 
include (dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>  
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->

<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>
<div class="well">
    <ul class="nav">
        <li ><a href="#home" data-toggle="tab">请填写功能资料</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
          <div class="tab-pane active in" id="home">
           <form id="tab" method="post">
                <label>名称 <i class="label label-important">*必填项</i></label>
                <input type="text" name="menuName" value="<?php echo $menu['menu_name']; ?>" class="input-xlarge" required="true">
                <label>链接 <i class="label label-important">*必填项</i><span class="label label-important">不可重复</span></label>
                <input type="text" name="menuUrl" value="<?php echo $menu['menu_url']; ?>" class="input-xlarge" required="true" >
                <label>所属模块 <i class="label label-important">*必填项</i></label>
                <?php
                if ($menu['menu_id'] > 100) {
                    echo "<select  name='moduleId' id='DropDownTimezone' class='input-xlarge' >";
                    foreach($moduleOpt as $key=>$options){
                    	if ($key == $menu['module_id']) {
                            echo "<option selected value=$key>$options</option>";   
                        } else {
                            echo "<option value=$key>$options</option>";
                        }
                    }
                            echo '</select>';
                 } else {
                    echo "<select  name='moduleId' id='DropDownTimezone' class='input-xlarge' disabled>";
                    foreach($moduleOpt as $kk=>$options){
                        if ($kk == $menu['module_id']) {
                            echo "<option selected value=$kk >$options</option>";
                        } else {
                            echo "<option value=$kk >$options</option>";
                        }
                    }
                    echo '</select>';
                }
                ?> 
                <label>是否显示为左侧菜单</label>
                <select name="isShow" class="input-xlarge" id='DropDownTimezone'>
                <?php 
                if ($menu['is_show']==1) {
                ?>
                    <option selected value=1>显示</option>
                    <option value=0>不显示</option>
                <?php 
                } else { 
                ?>
                    <option value=1>显示</option>
                    <option selected value=0>不显示</option>
                <?php 
                }
                ?>
                </select>
                <label>所属菜单</label>
                <select name="fatherMenu" id="DropDownTimezone" class="input-xlarge">
                <?php
                    echo '<option>无</option>';
                      foreach ($fatherMenuOpt  as $key=>$fatherMenus) {
                        foreach ($fatherMenus as $k=>$fathermenuInfo) {
                            if ($k==$menu['father_menu']){ 
                                echo "<option selected value=$k>$fathermenuInfo</option>";
                            } else {
                                echo "<option value=$k>$fathermenuInfo</option>";
                            }
                        }
                      }
                ?>
                </select>
                <label>是否有效</label>
                <select name="online" id="DropDownTimezone" class="input-xlarge">
                <?php 
                    if ($menu['online']==1) {
                ?>
                    <option selected value=1> 在线</option>
                    <option value=0>已下线</option>
                <?php 
                    } else { 
                ?>
                    <option value=1> 在线</option>
                    <option selected value=0>已下线</option>
                <?php 
                    }
                ?>
                </select>
                <label>是否允许快捷菜单 <span class="label label-important">修改 / 删除类链接不允许</span></label>
                <select name="shortcutAllowed" id="DropDownTimezone" class="input-xlarge">
                <?php 
                   if ($menu['shortcut_allowed']==1) {
                ?>
                    <option selected value=1> 允许</option>
                    <option value=0>不允许</option>
                <?php 
                    } else { 
                ?>
                    <option value=1 > 允许</option>
                    <option selected value=0 >不允许</option>
                <?php 
                    }
                ?>
                </select>
                <label>描述</label>
                <textarea name="menuDesc" rows="3" class="input-xlarge"><?php echo $menu['menu_desc']; ?></textarea>
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary"><strong>提交</strong></button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 -->
<?php 
include (dirname(__DIR__).'/footer.phtml');
?>
