<?php 
include (dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->
<div class="well">
    <ul class="nav">
      <li ><a href="#home" data-toggle="tab">请填写菜单模块资料</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane active in" id="home">
           <form id="tab" method="post" action="">
                <label>模块名称 <i class="label label-important">*必填项</i></label>
                <input type="text" name="moduleName" value="<?php echo $modules['module_name']; ?>" class="input-xlarge" >
                <label>模块链接 <i class="label label-important">*必填项</i></label>
                <input type="text" name="moduleUrl" value="<?php echo $modules['module_url']; ?>" class="input-xlarge" >
                <label>模块图标</label>
                <div style="width:20px;padding-bottom:5px">
                    <a class="icon" style="width:20px;line-height:2em;">
                    <i id="icon_preview" class="<?php echo $modules['module_icon']; ?>"></i></a>
                </div>
                <input type="text" readonly value="<?php echo $modules['module_icon']; ?>" name="moduleIcon" id="icon_id" style="width:180px" >
                <a id="icon_select" class="btn btn-info" style="vertical-align:top" >更改图标</a>
                <!--- 选择图标层--->
                <?php  include (dirname(__DIR__).'/iconSelect.phtml');?>
                <!--- 选择图标层 结束--->
                <label>模块排序数字<i class="label label-important">(数字越小越靠前)</i></label>
                <input type="text" name="moduleSort" value="<?php echo $modules['module_sort']; ?>" class="input-xlarge" >
                <label>是否有效</label>
                <?php 
                if ($modules['online'] == 1) {
                    echo "<select  name='online' id='DropDownTimezone' class='input-xlarge' disabled>";
                    foreach($moduleOnlineOptions as $k=>$options){
                    	if ($k == $module['online']) {
                            echo "<option selected>$options</option>";   
                        } else {
                        	echo "<option>$options</option>";
                        }
                    }
                    echo '</select>';
                 } else {
                    echo "<select  name='online' id='DropDownTimezone' class='input-xlarge'>";
                    foreach($moduleOnlineOptions as $k=>$options){
                    	if ($k == $module['online']) {
                    		echo "<option selected>$options</option>";
                    	} else {
                    	echo "<option>$options</option>";
                    	}
                    }                    	
                }
                ?>
                <label>描述</label>
                <textarea name="moduleDesc" rows="3" class="input-xlarge"><?php echo $modules['module_desc']?></textarea>
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary"><strong>提交</strong></button>
                </div>
        </form>
        </div>
    </div>
</div>
<script>
$('#icon_select').click(function(){	
    $('#myModal').modal({
        backdrop:true,
        keyboard:true,
        show:true
    });	
});

$('.icon').click(function(){
    var obj=$(this);
    $('#icon_preview').removeClass().addClass(obj.text());
    $('#icon_id').val(obj.text());
    $('#myModal').modal('toggle');
});
</script>
<!-- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 -->
<?php include(dirname(__DIR__).'/footer.phtml');?>
