<?php 
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->

<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>    
<div class="well">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">请填写账号资料</a></li>
    </ul>
    
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane active in" id="home">

            <form id="tab" method="post" action="add" autocomplete="off">
                <label>登录名</label>
                <input type="text" name="user_name" value="" class="input-xlarge" autofocus="true" required="true" >
                <label>密码</label>
                <input type="password" name="password" value="" class="input-xlarge" required="true" >
                <label>姓名</label>
                <input type="text" name="real_name" value="" class="input-xlarge" required="true" >
                <label>手机</label>
                <input type="text" name="mobile" value="" class="input-xlarge" required pattern="\d{11}">
                <label>邮件</label>
                <input type="email" name="email" value=""  class="input-xlarge" required="true" >
                <label>描述</label>
                <textarea name="user_desc" rows="3" class="input-xlarge"></textarea>
                <label>账号组</label>
<!--                 <{html_options name=user_group id="DropDownTimezone" class="input-xlarge" options=$group_options selected=0}> -->
                <select name="user_group" id="DropDownTimezone" class="input-xlarge">
                    <?php 
                    foreach($group_options as $k => $v){
                    ?>
                    <option value="<?php echo $k;?>"><?php echo $v;?></option>
                    <?php }?>
                </select>
            <div class="btn-toolbar">
                <button type="submit" class="btn btn-primary"><strong>提交</strong></button>
                <div class="btn-group"></div>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 -->
<?php include(dirname(__DIR__)."/footer.phtml"); ?>