<!DOCTYPE html>
<?php //die;?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>404页面报错啦！！！</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <script src="<?php echo Console\ADMIN_URL ?>assets/lib/jquery-1.8.1.min.js" ></script>
	<script src="<?php echo Console\ADMIN_URL ?>assets/js/jquery-ui.js"></script>
  </head>

<body>
    <img src="<?php echo Console\ADMIN_URL ?>assets/images/20151231.jpg" style="width:50%;height:50%;object-fit:cover;margin:50px 400px;">
    <div  id='show' style="margin:5px 0 0 700px;"></div>
</body>
<script type="text/javascript">
	var t=3;//设定跳转的时间 
	setInterval("refer()",1000); //启动1秒定时 
	function refer(){ 
	if(t==0){ 
	window.location.href="index"; //#设定跳转的链接地址 
	} 
	$('#show').html('<b>'+t+'秒后跳转到首页</b>');
	t--; // 计数器递减 
	} 
        
    </script>
</html>