<?php 
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->

<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>

<div class="well">
    <ul class="nav nav-tabs">
        <?php if ($change_password) { ?>
            <li ><a href="#home" data-toggle="tab">资料</a></li>
            <li class="active"><a href="#profile" data-toggle="tab">密码</a></li>
        <?php } else {?>
            <li class="active"><a href="#home" data-toggle="tab">资料</a></li>
            <li><a href="#profile" data-toggle="tab">密码</a></li>
        <?php }?>
    </ul>
    <div id="myTabContent" class="tab-content">
        <?php if ($change_password) {?>
            <div class="tab-pane fade" id="home">
        <?php } else {?>
            <div class="tab-pane active in" id="home">
        <?php }?>
            <form id="tab" method="post" action="profile" autocomplete="off">
                <label>登录名</label>
                <input type="text" name="user_name" value="<?php echo $user_info['user_name'];?>" class="input-xlarge" readonly="true">
                <label>姓名</label>
                <input type="text" name="real_name" value="<?php echo $user_info['real_name'];?>" class="input-xlarge">
                <label>手机</label>
                <input type="text" name="mobile" value="<?php echo $user_info['mobile'];?>" class="input-xlarge">
                <label>邮件</label>
                <input type="text" name="email" value="<?php echo $user_info['email'];?>" class="input-xlarge">
                <label>描述</label>
                <textarea name="user_desc" value="Smith" rows="3" class="input-xlarge"><?php echo $user_info['user_desc'];?></textarea>
                <hr />
                <label>显示QuickNote</label>	
<!--                 <{html_options name=show_quicknote id="DropDownTimezone" class="input-xlarge" options=$quicknoteOptions selected=$user_info.show_quicknote}> -->
                <select name="show_quicknote" id="DropDownTimezone" class="input-xlarge">
                    <?php foreach ($quicknoteOptions as $k=>$v) {?>
                    <option value="<?php echo $k;?>" <?php if ($user_info['show_quicknote'] == $k) {echo 'selected';}?>><?php echo $v;?></option>
                    <?php }?>
                </select>
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary"><i class="icon-save"></i> 保存</button>
                    <div class="btn-group"></div>
                </div>
            </form>
            </div>
        <?php if ($change_password) {?>
        <div class="tab-pane active in" id="profile">
        <?php } else {?>
        <div class="tab-pane fade" id="profile">
        <?php }?>
            <form id="tab2" method="post" action="" autocomplete="off">
                <input type="hidden" name="change_password" value="yes" >
                <label>原密码</label>
                <input type="password" name="old" class="input-xlarge">
                <label>新密码</label>
                <input type="password" name="new" class="input-xlarge">
                <div>
                    <button class="btn btn-primary">更新</button>
                </div>
            </form>
        </div>
    </div>
</div>
<?php include(dirname(__DIR__)."/footer.phtml"); ?>