<?php include(dirname(__DIR__).'/simple_header.tpl')?>
    <body> 
    <div class="navbar">
        <div class="navbar-inner">
            <ul class="nav pull-right">
            </ul>
                <a class="brand" href="<?php echo Console\ADMIN_URL;?>/index.php"><span class="first"></span> <span class="second"><?php echo Console\ADMIN_URL;?></span></a>
        </div>
    </div>
    <div>
        <div class="container-fluid"></div>	
        <div class="row-fluid"></div>
        <div class="http-error">
            <h1>Yep!</h1>
            <p class="info"><?php echo $message_detail;?></p> 
            <p><i class="icon-home"></i></p>
        </div>
    </div>
<?php include(dirname(__DIR__).'/footer.phtml');?>