<?php 
include (dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>  
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->
<?php 
 echo @$osadmin_action_alert;
 echo @$osadmin_quick_note;
?>
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">请填写quick note</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
          <div class="tab-pane active in" id="home">
           <form id="tab" method="post" action="">
                <label><span class="label label-info">不支持HTML代码</span></label>
                <textarea name="noteContent" rows="3" class="input-xlarge" required="true"><?php echo $quickNote['note_content']; ?></textarea>
                <div class="btn-toolbar">
                <button type="submit" class="btn btn-primary"><strong>提交</strong></button>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 -->
<?php 
include (dirname(__DIR__).'/footer.phtml');
?>