<? 
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!--- START 以上内容不需更改，保证该TPL页内的标签匹配即可 --->

<? 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>

<div style="border:0px;padding-bottom:5px;height:auto">
    <form action="list" method="GET" style="margin-bottom:0px">
    <div style="float:left;margin-right:5px">
        <label> 选择起始时间 </label>
        <input type="text" id="start_date" name="start_date" value="<?php echo @$_GET['start_date'];?>" placeholder="起始时间" >
    </div>
    <div style="float:left;margin-right:5px">
        <label>选择结束时间</label>
        <input type="text" id="end_date" name="end_date" value="<?php echo @$_GET['end_date'];?>" placeholder="结束时间" > 
    </div>
    <div class="btn-toolbar" style="padding-top:15px;padding-bottom:0px;margin-bottom:0px;float:left">
        <button type="submit" class="btn btn-primary"><strong>检索</strong></button>
    </div>
    <div style="clear:both;"></div>
    </form>
</div>
    <div class="block">
        <a href="#page-stats" class="block-heading" data-toggle="collapse">数据记录</a>
        <div id="page-stats" class="block-body collapse in">
               <table class="table table-striped">
              <thead>
                <tr>
                    <th style="width:150px">日期</th>
                    <th style="width:150px">标题</th>
                    <th style="width:150px">创建人</th>
                    <th style="width:150px">活动ID</th>
                    <th style="width:150px">有无照片</th>
                    <th style="width:150px">有无分享</th>
                </tr>
              </thead>
              <tbody>
                  <?php foreach ($events as $event) {?>
                  <tr>
                      <td><?php echo $event['create_time']?></td>
                      <td><?php echo $event['name']?></td>
                      <td><?php echo $event['uid']?></td>
                      <td><?php echo $event['id']?></td>
                      <td><?php if (!empty($event['count_pictures'])) {echo '有';} else {echo '无';}?></td>
                      <td><?php echo '无';?></td>
                  </tr>
                  <?php }?>
              </tbody>
            </table>
                <!--- START 分页模板 --->
                <?php echo $page_html;?>
                <!--- END --->
        </div>
    </div>

<script>
$(function() {
	var date=$( "#start_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
$(function() {
	var date=$( "#end_date" );
	date.datepicker({ dateFormat: "yy-mm-dd" });
	date.datepicker( "option", "firstDay", 1 );
});
$(function() {
	var html='';
	html+='<option value="0">--请选择--</option>';
	html+='<option value="1">日活跃用户</option>';
	html+='<option value="2">男日活跃</option>';
	html+='<option value="3">女日活跃</option>';
	html+='<option value="4">新增用户</option>';
	html+='<option value="5">男日新增</option>';
	html+='<option value="6">女日新增</option>';
	html+='<option value="7">Android日新增</option>';
	html+='<option value="8">IOS日新增</option>';
	html+='<option value="9">手机号注册</option>';
	html+='<option value="10">QQ注册</option>';
	html+='<option value="11">微信注册</option>';
	html+='<option value="12">微博注册</option>';
	$('#classify').html(html);
	
})
$(function() {
	$('select').change(function(){
		var start_date=$('#start_date').val();
        var end_date=$('#end_date').val();
        var classify=$(this).val();
        $.ajax({
            'type':'post',
            'url':'addActive',
            'data':{'start_date':start_date,
                    'end_date':end_date,
                    'classify':classify},
            'success':function(e){
                    $('#sum').val(e);
                }
            },'json')
	})
    
})
</script>
	
<!--- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 --->
<?php include(dirname(__DIR__)."/footer.phtml"); ?>