<?php 
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->

<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>

<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">时区设置</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane active in" id="home">
            <form id="tab" method="post" action="" autocomplete="off">
                <label>选择时区</label>	
<!--             <{html_options name=new_timezone id="DropDownTimezone" class="input-xlarge" options=$timezone_options selected=$timezone }> -->
                <select name="new_timezone" id="DropDownTimezone" class="input-xlarge">
                    <?php foreach ($timezone_options as $k=>$v) {?>
                    <option value="<?php echo $k;?>" <?php if ($timezone == $k) {echo 'selected';}?>><?php echo $v;?></option>
                    <?php }?>
                </select>
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary"><i class="icon-save"></i> 保存</button>
                    <div class="btn-group"></div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
<?php include(dirname(__DIR__)."/footer.phtml"); ?>