<?php include(dirname(__DIR__).'/header.phtml');?>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <ul class="nav pull-right">
            </ul>
            <a class="brand" href="<?php echo Console\ADMIN_URL;?>Console/User/index"><span class="first"></span> <span class="second"><?php echo Console\COMPANY_NAME;?></span></a>
        </div>
    </div>
<div>
<div class="container-fluid">
<div class="row-fluid">
    <div class="http-error">
    <p></p>
        <h1>Oops!</h1>
        <p class="info"><?php echo $message_detail;?></p>
        <p><h3><a href="<?php echo Console\ADMIN_URL.$forward_url;?>"><?php echo $forward_title;?></a></h3></p>
    </div>
<?php include(dirname(__DIR__).'/footer.phtml');?>