<?php include (dirname(__DIR__).'/header.phtml'); ?>
<?php include (dirname(__DIR__).'/menu/navibar.phtml');?>
<?php include (dirname(__DIR__).'/menu/sideBar.phtml');?>
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->
<?php 
 echo @$osadmin_action_alert;
 echo @$osadmin_quick_note;
?>

<div class="well">
    <ul class="nav">
      <li class="active"><a href="#home" data-toggle="tab">账号组成员列表</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane active in" id="home">
            <form id="tab" method="post" action="">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="checkAll">全选</th>
                            <th>#</th>
                            <th>登录名</th>
                            <th>姓名</th>
                            <th>手机</th>
                            <th >邮箱</th>
                            <th >登录时间</th>
                            <th >登录IP</th>
                            <th >Group#</th>
                            <th>描述</th>
                        </tr>
                    </thead>
              <tbody>
                <?php foreach ($user_infos as $user_info) {?>
                    <tr>
                        <td><input type="checkbox" name="user_ids[]" value="<?php echo $user_info['user_id'];?>" <?php if ($user_info['user_id'] == 1) { echo 'disabled';}?>></td>
                        <td><?php echo $user_info['user_id'];?></td>
                        <td><?php echo $user_info['user_name'];?></td>
                        <td><?php echo $user_info['real_name'];?></td>
                        <td><?php echo $user_info['mobile'];?></td>
                        <td><?php echo $user_info['email'];?></td>
                        <td><?php echo $user_info['login_time'];?></td>
                        <td><?php echo $user_info['login_ip'];?></td>
                        <td><?php echo $user_info['user_group'];?></td>
                        <td><?php echo $user_info['user_desc'];?></td>
                        </tr>
                 <?php }?>
            </tbody>
        </table> 
        <label>选择账号组</label>
        <select name = "user_group" id = "DropDownTimezone" class = "input-xlarge">
            <?php foreach ($groupOptions as $key=>$option) {?>
                <option value=<?php echo $key; ?>><?php echo $option;?></option>
            <?php }?>
        </select>
        <div class="btn-toolbar">
            <button type="submit" class="btn btn-primary"><strong>修改账号组</strong></button>
        </div>
    </form>
    </div>
</div>

<!---操作的确认层，相当于javascript:confirm函数--->
<?php echo @$osadmin_action_confirm;?>

<script type="text/javascript">
$("#checkAll").click(function(){
	var bischecked=$('#checkAll').is(':checked');
    //if($(this).attr("checked")){
    if (bischecked) {
        $("input[type='checkbox']").attr("checked","checked");
    }else{
        $("input[type='checkbox']").attr("checked",false);
    }
});
</script>

<!-- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 -->
<?php include(dirname(__DIR__).'/footer.phtml');?>