<?php 
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!--- START 以上内容不需更改，保证该TPL页内的标签匹配即可 --->

<?php 
 echo @$osadmin_action_alert;
 echo @$osadmin_quick_note;
?>
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active">请填写账号组资料</li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane active in" id="home">
            <form id="tab" method="post" action="">
                <label>账号组名称</label>
                <input type="text" name="group_name" value="<?php echo $group['group_name']?>" class="input-xlarge" required="true" autofocus="true" >
                <input type="hidden" name="group_id" value="<?php echo $group['group_id']?>">
                <label>描述</label>
                <textarea name="group_desc" rows="3" class="input-xlarge"><?php echo $group['group_desc']?></textarea>
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary"><strong>提交</strong></button>
                </div>
            </form>
        </div>
    </div>
</div>
<?php echo @$osadmin_action_confirm;?>
<!-- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 -->
<?php include(dirname(__DIR__).'/footer.phtml');?>