<?php 
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->

<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>    
<div class="well">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">请填写启动图资料</a></li>
    </ul>
    <div class="btn-toolbar">
        <?php if ($img['platform'] == 0) {?>
        <button id="android" class="btn btn-primary">android</button>
        <?php } else {?>
        <button id="ios" class="btn btn-primary" style="width:78px">ios</button>
        <?php }?>
    </div>
    <?php if ($img['platform'] == 0) {?>
    <div id="myTabContent1" class="tab-content">
        <div class="tab-pane active in" id="home">
            <form id="tab1" method="post" action="modify" autocomplete="off" enctype="multipart/form-data">
                <input type="hidden" name="img_id" value="<?php echo $img['id']?>">
                <label>启动图</label>
                <input type="file" name="android" required="true" style="width:180px"><img src="http://<?php echo Us\Config\DOWNLOAD_DOMAIN?>/images/splash/<?php echo $img['images']['android']?>.jpg" style="width:80px;height:80px;object-fit:cover">
                <label>标题</label>
                <input type="text" name="title" value="<?php echo $img['title']?>" required="true" placeholder="标题" style="width:206px">
                <label>跳转地址</label>
                <input type="text"  name="skip_url" value="<?php echo $img['skip_url']?>" required="true" placeholder="跳转地址">
                <label>时间控制</label>
                <input type="text"  name="duration" value="<?php echo $img['duration']?>" placeholder="时间控制">
                <label>启动图是否允许跳过</label>
                <select name="can_skip">
                    <option value="0" <?php if ($img['can_skip'] == 0) {echo 'selected';}?>>否</option>
                    <option value="1" <?php if ($img['can_skip'] == 1) {echo 'selected';}?>>是</option>
                </select>
                <label>类型</label>
                <select name="type" required="true">
                    <option value="0">--请选择--</option>
                    <option value="1" <?php if ($img['action_type'] == 1) {echo 'selected';}?>>Web</option>
                    <option value="2" <?php if ($img['action_type'] == 2) {echo 'selected';}?>>现场</option>
                </select>
                <label>版本码</label>
                <?php 
                foreach ($package_datas as $package_data) {
                    if ($package_data['platform'] == 0) {
                ?>
                <input type="checkbox"  name="code[]" value="<?php echo $package_data['code'];?>" style="margin:0px;" <?php foreach ($img['code'] as $v) {if ($v == $package_data['code']) {echo 'checked';}}?>><?php echo $package_data['code'];?>
                <?php }}?>
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary"><strong>提交</strong></button>
                    <div class="btn-group"></div>
                </div>
            </form>
        </div>
    </div>
    <?php } else {?>
    <div id="myTabContent2" class="tab-content">
        <div class="tab-pane active in" id="home">
            <form id="tab2" method="post" action="modify" autocomplete="off" enctype="multipart/form-data">
                <input type="hidden" name="img_id" value="<?php echo $img['id']?>">
                <label>ios4</label>
                <input type="file" name="ios4" required="true" style="width:180px"><img src="http://<?php echo Us\Config\DOWNLOAD_DOMAIN?>/images/splash/<?php echo $img['images']['ios4']?>.jpg" style="width:40px;height:40px;object-fit:cover" >
                <label>ios5</label>
                <input type="file" name="ios5" required="true" style="width:180px"><img src="http://<?php echo Us\Config\DOWNLOAD_DOMAIN?>/images/splash/<?php echo $img['images']['ios5']?>.jpg" style="width:40px;height:40px;object-fit:cover" >
                <label>ios6</label>
                <input type="file" name="ios6" required="true" style="width:180px"><img src="http://<?php echo Us\Config\DOWNLOAD_DOMAIN?>/images/splash/<?php echo $img['images']['ios6']?>.jpg" style="width:40px;height:40px;object-fit:cover" >
                <label>ios6s</label>
                <input type="file" name="ios6s" required="true" style="width:180px"><img src="http://<?php echo Us\Config\DOWNLOAD_DOMAIN?>/images/splash/<?php echo $img['images']['ios6s']?>.jpg" style="width:40px;height:40px;object-fit:cover" >
                <label>标题</label>
                <input type="text" name="title" value="<?php echo $img['title']?>" required="true" placeholder="标题" style="width:206px">
                <label>跳转地址</label>
                <input type="text"  name="skip_url" value="<?php echo $img['skip_url']?>" required="true" placeholder="跳转地址">
                <label>时间控制</label>
                <input type="text"  name="duration" value="<?php echo $img['duration']?>" placeholder="时间控制">
                <label>启动图是否允许跳过</label>
                <select name="can_skip">
                    <option value="0" <?php if ($img['can_skip'] == 0) {echo 'selected';}?>>否</option>
                    <option value="1" <?php if ($img['can_skip'] == 1) {echo 'selected';}?>>是</option>
                </select>
                <label>选择类型</label>
                <select name="type" required="true">
                    <option value="0">--请选择--</option>
                    <option value="1" <?php if ($img['action_type'] == 1) {echo 'selected';}?>>Web</option>
                    <option value="2" <?php if ($img['action_type'] == 2) {echo 'selected';}?>>现场</option>
                </select>
                <label>版本码</label>
                <?php foreach ($package_datas as $package_data) {
                        if ($package_data['platform'] == 1) {
                ?>
                <input type="checkbox"  name="code[]" value="<?php echo $package_data['code'];?>" style="margin:0px;" <?php foreach ($img['code'] as $v) {if ($v == $package_data['code']) {echo 'checked';}}?>><?php echo $package_data['code'];?>
                <?php }}?>
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary"><strong>提交</strong></button>
                    <div class="btn-group"></div>
                </div>
            </form>
        </div>
    </div>
    <?php }?>
</div>
<!-- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 -->
<?php include(dirname(__DIR__)."/footer.phtml"); ?>