<?php 
include(dirname(__DIR__).'/header.phtml');
include(dirname(__DIR__)."/menu/navibar.phtml");
include(dirname(__DIR__)."/menu/sideBar.phtml");
?>
<!-- START 以上内容不需更改，保证该TPL页内的标签匹配即可 -->

<?php 
echo @$osadmin_action_alert;
echo @$osadmin_quick_note;
?>    
<div class="well">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">请填写活动地址</a></li>
    </ul>
    <div class="btn-toolbar">
        <button id="android" class="btn btn-primary">android</button>
        <button id="ios" class="btn" style="width:78px">ios</button>
    </div>
    
    <div id="myTabContent1" class="tab-content">
        <div class="tab-pane active in" id="home">
            <form id="tab1" method="post" action="pushAndroidEventAddress" autocomplete="off">
                <label>聚会地址</label>
                <input type="text" name="party" style="width:206px">
                <label>旅行地址</label>
                <input type="text" name="travel" style="width:206px">
                <label>婚礼地址</label>
                <input type="text" name="wedding" style="width:206px">
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary"><strong>推送</strong></button>
                    <div class="btn-group"></div>
                </div>
            </form>
        </div>
    </div>
    <div id="myTabContent2" class="tab-content">
        <div class="tab-pane active in" id="home">
            <form id="tab2" method="post" action="pushEventAddress" autocomplete="off" enctype="multipart/form-data"  style="display:none">
                <label>聚会地址</label>
                <input type="text" name="party" style="width:206px">
                <label>旅行地址</label>
                <input type="text"  name="travel" value="" >
                <label>婚礼地址</label>
                <input type="text"  name="wedding" value="" >
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary"><strong>推送</strong></button>
                    <div class="btn-group"></div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
$(function() {
	$('#android').click(function() {
	    $(this).addClass('btn-primary').siblings().removeClass('btn-primary');
	    $('#tab1').show();
	    $('#tab2').hide();
	})
	$('#ios').click(function() {
	    $(this).addClass('btn-primary').siblings().removeClass('btn-primary');
	    $('#tab2').show();
	    $('#tab1').hide();
	})
})
</script>
<!-- END 以下内容不需更改，请保证该TPL页内的标签匹配即可 -->
<?php include(dirname(__DIR__)."/footer.phtml"); ?>